Praksa/Controllers/PoduzecaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Praksa.Models;
using Praksa.Reports;
using System.IO;

namespace Praksa.Controllers
{
    [Authorize]
    public class PoduzecaController : Controller
    {
        private PraksaDbContext db = new PraksaDbContext();

        // GET: Poduzeca

        public ActionResult Index()
        {
            Student student = db.studenti.Single(s => s.mail == User.Identity.Name);
            ViewBag.prijavljen = student.prijavljen;
            if (User.IsInRole("student"))
            {
                List<Poduzeca> lista = new List<Poduzeca>();
                foreach (Poduzeca p in db.poduzeca.ToList()) {
                    if (p.aktivno)
                        lista.Add(p);
                }
                return View(lista);
            }

            return View(db.poduzeca.ToList());
        }


        [Authorize(Roles = "student")]
        public ActionResult Prijavi(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poduzeca poduzeca = db.poduzeca.Find(id);
            if (poduzeca == null)
            {
                return HttpNotFound();
            }
            return View(poduzeca);
        }

        [Authorize(Roles = "student")]
        public ActionResult PrijaviP(int? id)
        {
            Student student = db.studenti.Single(s => s.mail == User.Identity.Name);
            if (student.prijavljen)
            {
                return Content("Već imate prijavljenu praksu");
            }
            student.prijavljen = true;
            Poduzeca poduzeca = db.poduzeca.Find(id);
            Prakse prakse = new Prakse()
            {
                MBRStudenta = student.maticniBroj,
                id_poduzeca = poduzeca.id_poduzeca,
                godina = DateTime.Now.Year,
                datumPocetka = DateTime.Now.Date,
                datumKraja = DateTime.Now.Date
            };
            poduzeca.brojStudenata++;
            db.Entry(poduzeca).State = EntityState.Modified;
            db.Entry(student).State = EntityState.Modified;
            db.prakse.Add(prakse);
            db.SaveChanges();
            

            return RedirectToAction("Index");
        }

        // GET: Poduzeca/Create
        public ActionResult Predlozi()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Predlozi([Bind(Include = "nazivPoduzeca,adresa,mail,url,telefon,faks,odgovornaOsoba,opisPoduzeca")] Poduzeca poduzeca)
        {
            if (ModelState.IsValid)
            {
                db.poduzeca.Add(poduzeca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(poduzeca);
        }

        [Authorize(Roles = ("admin"))]
        // GET: Poduzeca/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poduzeca poduzeca = db.poduzeca.Find(id);
            if (poduzeca == null)
            {
                return HttpNotFound();
            }
            return View(poduzeca);
        }


        [HttpPost]
        [Authorize(Roles = ("admin"))]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_poduzeca,nazivPoduzeca,adresa,mail,url,telefon,faks,odgovornaOsoba,opisPoduzeca")] Poduzeca poduzeca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(poduzeca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(poduzeca);
        }

        // GET: Poduzeca/Delete/5
        [Authorize(Roles = ("admin"))]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poduzeca poduzeca = db.poduzeca.Find(id);
            if (poduzeca == null)
            {
                return HttpNotFound();
            }
            return View(poduzeca);
        }

        // POST: Poduzeca/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = ("admin"))]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Poduzeca poduzeca = db.poduzeca.Find(id);
            db.poduzeca.Remove(poduzeca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileStreamResult Ispisi()
        {
            // EF - lista sa filtriranjem
            var popis = from s in db.poduzeca select s;

            //ToList() je bitan ako želimo izbjeći deferred execution i lazy loading mehanizme EF-a
            AdministracijaReport r = new AdministracijaReport(popis.ToList());
            return new FileStreamResult(new MemoryStream(r.Podaci), "application/pdf");

            // ovako odmah ide download
            // return File(path, "application/pdf", "Popis_studenata.pdf");

            // ovako se otvara unutar preglednika
            // return File(path, "application/pdf");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize (Roles = "admin")]
        public ActionResult AktivirajDeaktiviraj(int? id) {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poduzeca poduzeca = db.poduzeca.Find(id);
            if (poduzeca == null)
            {
                return HttpNotFound();
            }
            if (poduzeca.aktivno)
                poduzeca.aktivno = false;
            else
                poduzeca.aktivno = true;
            db.Entry(poduzeca).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Praksa/Controllers/PrakseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Praksa.Models;
using System.IO;
using System.Web.Hosting;

namespace Praksa.Controllers
{
    [Authorize]
    public class PrakseController : Controller
    {
        private PraksaDbContext db = new PraksaDbContext();

        // GET: Prakse
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            List <PraksePomocna> lista = new List<PraksePomocna>();

            foreach (Prakse p in db.prakse.ToList())
            {
                Student s = db.studenti.Find(p.MBRStudenta);
                Poduzeca pod = db.poduzeca.Find(p.id_poduzeca);
                PraksePomocna pp = new PraksePomocna
                {
                    id = p.idpraksa,
                    mbr = s.maticniBroj,
                    ime = s.ime,
                    prezime = s.prezime,
                    nazivPoduzeca = pod.nazivPoduzeca,
                    godina = p.godina,
                    pocetak = p.datumPocetka,
                    kraj = p.datumKraja,
                    zakljucano = p.zakljucano,
                    zavrseno = p.zavrseno   
                };
                lista.Add(pp);
            }
            return View(lista);
        }

        [Authorize (Roles = "admin")]
        public ActionResult Zakljucaj(int? id)
        {
            Prakse p = db.prakse.Find(id);
            if (p == null)
                return HttpNotFound();
            if (p.zakljucano)
                p.zakljucano = false;
            else
                p.zakljucano = true;
            db.Entry(p).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize (Roles = "student")]
        public ActionResult Edit()
        {
            Student s = db.studenti.Single(x => x.mail==User.Identity.Name.ToString());
            Prakse p;
            try { db.prakse.Single(x => x.MBRStudenta == s.maticniBroj && x.godina == DateTime.Now.Year); } catch
            {
                return RedirectToAction("NemaPrakse");
            }
            p = db.prakse.Single(x => x.MBRStudenta == s.maticniBroj && x.godina == DateTime.Now.Year);
            if (p == null)
                return HttpNotFound();
            Poduzeca pod = db.poduzeca.Find(p.id_poduzeca);
            PraksePomocna pp = new PraksePomocna
            {
                id = p.idpraksa,
                mbr = s.maticniBroj,
                ime = s.ime,
                prezime = s.prezime,
                nazivPoduzeca = pod.nazivPoduzeca,
                godina = p.godina,
                pocetak = p.datumPocetka,
                kraj = p.datumKraja,
                zakljucano = p.zakljucano,
                zavrseno = p.zavrseno
            };
            return View(pp);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,pocetak,kraj")] PraksePomocna praksa)
        {
            if (praksa.pocetak > praksa.kraj)
                return Content("Početak prakse je veći od kraja");

            Prakse p = db.prakse.Find(praksa.id);
            p.datumPocetka = praksa.pocetak;
            p.datumKraja = praksa.kraj;
            if (ModelState.IsValid)
            {
                db.Entry(p).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }
            return View(praksa);
        }

        [Authorize(Roles = "student")]
        public ActionResult Odjavi(int? id)
        {
            Student s = db.studenti.Single(x => x.mail == User.Identity.Name);
            Prakse p = db.prakse.Find(id);
            Poduzeca pod = db.poduzeca.Find(p.id_poduzeca);
            pod.brojStudenata--;
            s.prijavljen = false;
            db.Entry(s).State = EntityState.Modified;
            db.Entry(pod).State = EntityState.Modified;
            db.prakse.Remove(p);
            db.SaveChanges();

            return RedirectToAction("Edit");
        }

        public ActionResult NemaPrakse() {
            return View();
        }

        [Authorize (Roles = "student")]
        public ActionResult Zabiljeska(int? idpr) {
            Prakse p = db.prakse.Find(idpr);
            if(DateTime.Now.Date < p.datumPocetka || DateTime.Now.Date > p.datumKraja)
            {
                return Content("Zabilješke se mogu upisivati samo tokom trajanja prakse.");
            }
            Dnevnik d = null;
            try
            {
                DateTime n = DateTime.Now.Date;
                d = db.dnevnik.Single(x => x.idpraksa == idpr && x.datum == n);
            }
            catch
            {
                d = new Dnevnik()
                {
                    idpraksa = (int)idpr,
                    zabiljeska = "",
                    datum = DateTime.Now.Date
                };
                db.dnevnik.Add(d);
                db.SaveChanges();
            }
            return View(d);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Zabiljeska([Bind(Include = "iddnevnik,zabiljeska")] Dnevnik d)
        {
            Dnevnik n = db.dnevnik.Find(d.iddnevnik);
            n.zabiljeska = d.zabiljeska;
            db.Entry(n).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Edit");
        }

        [Authorize (Roles ="admin")]
        public ActionResult Biljeske(int? id)
        {
            Prakse p = db.prakse.Find(id);
            if (p == null)
            {
                return Content("Praksa nije pronađena.");
            }
            List<Dnevnik> lista = new List<Dnevnik>();
            foreach(Dnevnik d in db.dnevnik)
            {
                if (p.idpraksa == d.idpraksa)
                    lista.Add(d);
            }

            return View(lista);
        }

        public ActionResult Dokumenti(int? id) {
            Prakse p = db.prakse.Find(id);
            if (p == null)
            {
                return Content("Praksa nije pronađena.");
            }
            ViewBag.id = id;

            List<Dokument> lista = new List<Dokument>();
            foreach(Dokument d in db.dokumenti)
            {
                if(p.idpraksa == d.idprakse)
                {
                    lista.Add(d);
                }
            }
            return View(lista);
        }

        [HttpPost]
        public ActionResult Dokumenti(HttpPostedFileBase file,int id)
        {
            if (file.ContentLength > 0)
            {
                int godina = DateTime.Now.Year;
                var path = HostingEnvironment.ApplicationPhysicalPath + @"\Dokumenti\";
                if(DateTime.Now.Date<new DateTime(DateTime.Now.Year, 10, 1))
                {
                    if(!Directory.Exists(path + "godina_" + (godina - 1) + "_" + godina))
                        Directory.CreateDirectory(path + "godina_" + (godina - 1) + "_" + godina);
                    path += "godina_" + (godina - 1) + "_" + godina+"\\";

                }
                else if(DateTime.Now.Date > new DateTime(DateTime.Now.Year, 10, 1))
                {
                    if(!Directory.Exists(path + "godina_" + (godina + 1) + "_" + godina))
                        Directory.CreateDirectory(path + "godina_" + (godina + 1) + "_" + godina);
                    path += path + "godina_" + (godina + 1) + "_" + godina+"\\";
                }
            

                int x = db.dokumenti.Count(y => y.idprakse == id);
                x++;

                Dokument d = new Dokument();
                var fileName = Path.GetFileName(file.FileName);
                var fileEx = Path.GetExtension(file.FileName);
                d.dokument = fileName;
                path += "Dok_" + x + fileEx;
                file.SaveAs(path);
                d.put = path;
                d.idprakse = id;
                
                db.dokumenti.Add(d);
                db.SaveChanges();
            }
            return RedirectToAction("Dokumenti");
        }

        public FileResult Preuzmi(string put, string file) {
            FileInfo f = new FileInfo(put);
            return File(put, f.Extension, file);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Praksa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Praksa</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Praksa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Administracija", "Index" , "Administracija")</li>
                    <li>@Html.ActionLink("Poduzeća", "Index", "Poduzeca")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Praksa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Praksa/Views/Shared/_MyLayoutView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_MyLayoutView</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Praksa/Views/Shared/_mylajout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Praksa</title>
    <meta charset="utf-8" />
    @*@<link rel="stylesheet" type="text/css" href=@Url.Content("~Content/Mojtemplet/style/style.css") />*@
    @Styles.Render("~/Content/Mojtemplet/style/style.css")
    @Scripts.Render("~/bundles/modernizr")
   
    </head>
    <body>
        <div id="main">
            <div id="header">
                <div id="logo">
                    <div id="logo_text">
                        <!-- class="logo_colour", allows you to change the colour of the text -->
                        <h1>@Html.ActionLink("Praksa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })<span class="logo_colour"></span></h1>
                        
                    </div>
                </div>
                <div id="menubar" >
                    <ul  id="menu">
                        <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
                        @if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Administracija", "Index", "Administracija", new { area = "" }, new { @class = "navbar-brand" })</li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Poduzeća", "Index", "Poduzeca", new { area = "" }, new { @class = "navbar-brand" })</li>
                            if (User.IsInRole("student"))
                            {
                                <li>@Html.ActionLink("Praksa", "Edit", "Prakse", new { area = "" }, new { @class = "navbar-brand" })</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Praksa", "Index", "Prakse", new { area = "" }, new { @class = "navbar-brand" })</li>
                            }
                        }

                       
                        <li>@Html.Partial("_LoginPartial")</li>
                        

                    </ul>

                </div>
               
            </div>
            <div>
                @RenderBody()
            </div>
          
           
        </div>
       
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>